% material_packing_reference.m
% Reference for POGO anisotropic material parameter packing.
%
% IMPORTANT:
% The packing order below matches the validated POGO style used in the
% layered-composite example. Do not replace it with a naive matrix reshape.
% Also note that the Cij ordering here is not the same as Bunge-convention
% indexing used elsewhere for orientation descriptions.

% Example usage:
% D = D_EG7781;
% rho = rho_C3K;
% model.matTypes{1,1}.paramsType = 2;
% model.matTypes{1,1}.paramValues = [D(1,1); D(1,2); D(2,2); ...
%                                    D(1,3); D(2,3); D(3,3); ...
%                                    D(1,6); D(2,6); D(3,6); D(6,6); ...
%                                    D(1,5); D(2,5); D(3,5); D(6,5); D(5,5); ...
%                                    D(1,4); D(2,4); D(3,4); D(6,4); D(5,4); D(4,4); ...
%                                    rho; 0];

function packed = material_packing_reference(D, rho)
packed = [D(1,1); D(1,2); D(2,2); ...
          D(1,3); D(2,3); D(3,3); ...
          D(1,6); D(2,6); D(3,6); D(6,6); ...
          D(1,5); D(2,5); D(3,5); D(6,5); D(5,5); ...
          D(1,4); D(2,4); D(3,4); D(6,4); D(5,4); D(4,4); ...
          rho; 0];
end
